language: go

os:
  - linux
  #- osx

go:
  - 1.9.x

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get update -y;
        sudo apt-get install libasound2-dev libxi-dev libxinerama-dev libxcursor-dev libxxf86vm-dev libxrandr-dev -y;
    fi

install:
  - go get -t ./...
